import test from "node:test";
import assert from "node:assert/strict";
import express from "express";
import mongoose from "mongoose";
import jwt from "jsonwebtoken";
import siteRoutes from "../routes/site.js";
import Service from "../models/Service.js";
import SiteSettings from "../models/SiteSettings.js";
import AdminCredentials from "../models/AdminCredentials.js";
import { notifySiteChanges } from "./siteEvents.js";
import { siteCache } from "./siteCache.js";
import { apiErrorHandler } from "./router.js";
import { DEFAULT_DRIVER_PRICING } from "../shared/driverPricing.js";

test("admin API saves plans, refreshes public cached prices and rejects invalid rates", async (t) => {
  const previousState = mongoose.connection.readyState;
  mongoose.connection.readyState = 1;
  t.after(() => { mongoose.connection.readyState = previousState; siteCache.clear(); });
  let stored = { _id: "507f1f77bcf86cd799439011", slug: "driver-only", name: "Driver Only", isActive: true };
  let reads = 0;
  t.mock.method(SiteSettings, "findOne", () => ({ lean: async () => ({ defaultServicesImported: true }) }));
  t.mock.method(AdminCredentials, "findById", async () => null);
  t.mock.method(Service, "find", () => ({ sort: () => ({ lean: async () => { reads++; return [structuredClone(stored)]; } }) }));
  t.mock.method(Service, "findByIdAndUpdate", async (_id, updates) => {
    const document = new Service({ ...stored, ...updates });
    await document.validate();
    stored = document.toObject();
    return document;
  });
  const app = express();
  app.use(express.json(), notifySiteChanges);
  app.use("/api", siteRoutes);
  app.use(apiErrorHandler);
  const server = app.listen(0, "127.0.0.1");
  await new Promise(resolve => server.once("listening", resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}/api/services`;
  const headers = { "Content-Type": "application/json", Authorization: `Bearer ${jwt.sign({ role: "admin" }, process.env.JWT_SECRET || "development-only-change-this-jwt-secret")}` };
  siteCache.clear();
  const first = await (await fetch(base)).json();
  assert.equal(first[0].driverPricing.plans[0].price, 499);
  await Promise.all([fetch(base), fetch(base), fetch(base)]);
  assert.equal(reads, 1);
  const pricing = structuredClone(DEFAULT_DRIVER_PRICING);
  pricing.plans[0].price = 599;
  pricing.plans[0].label = "Local rides";
  const saved = await fetch(`${base}/${stored._id}`, { method: "PUT", headers, body: JSON.stringify({ driverPricing: pricing }) });
  assert.equal(saved.status, 200);
  const updated = await (await fetch(base)).json();
  assert.equal(updated[0].driverPricing.plans[0].price, 599);
  assert.equal(updated[0].driverPricing.plans[0].label, "Local rides");
  assert.equal(reads, 2);
  const invalid = await fetch(`${base}/${stored._id}`, { method: "PUT", headers, body: JSON.stringify({ driverPricing: { ...pricing, additionalHourlyRate: -10 } }) });
  assert.equal(invalid.status, 400);
  const unauthorized = await fetch(`${base}/${stored._id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ driverPricing: pricing }) });
  assert.equal(unauthorized.status, 401);
});
